# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/AD/experiment/ad9280_ethernet/adc_ethernet.srcs/sources_1/ip/fft_ls/fft_ls.xci
# IP: The module: 'fft_ls' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/AD/experiment/ad9280_ethernet/adc_ethernet.srcs/sources_1/ip/fft_ls/fft_ls_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_ls'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/AD/experiment/ad9280_ethernet/adc_ethernet.srcs/sources_1/ip/fft_ls/fft_ls.xci
# IP: The module: 'fft_ls' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/AD/experiment/ad9280_ethernet/adc_ethernet.srcs/sources_1/ip/fft_ls/fft_ls_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_ls'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
